"use client";

import { useMemo } from "react";

import { RefreshIcon, TrashIcon } from "@/components/icons";
import { TintButton } from "@/components/ui/buttons";
import { PackageBadge } from "@/components/ui/Badge";
import { Card, CardHeader } from "@/components/ui/Card";
import { Cell, DataTable, EmptyRow, Row } from "@/components/ui/Table";
import { useToast } from "@/components/ui/Toast";
import { del } from "@/lib/client-api";
import { useDashboard } from "@/lib/store";

const COLUMNS = ["License Key", "Package", "Duration", "Creator", "Created On"];

export default function ResellerHistoryPage() {
  const toast = useToast();
  const refresh = useDashboard((s) => s.refresh);
  const isOwner = useDashboard((s) => s.user?.role === "OWNER");
  // Same as the owner history: derive from a stable slice, never from a
  // selector that allocates.
  const keyHistory = useDashboard((s) => s.db.cheatExeKeyHistory);
  const history = useMemo(() => keyHistory.filter((k) => k.creator !== "admin"), [keyHistory]);

  const clear = async () => {
    if (!confirm("Clear this key history permanently?")) return;
    try {
      await del("/api/history?scope=reseller");
      await refresh();
      toast("Key history cleared successfully.", "success");
    } catch (err) {
      toast((err as Error).message, "error");
    }
  };

  return (
    <Card flat>
      <CardHeader
        title={isOwner ? "Reseller Key History" : "My Key History"}
        subtitle="Keys generated by resellers."
        actions={
          <>
            <TintButton
              tone="green"
              onClick={async () => {
                await refresh();
                toast("Key history refreshed.", "success");
              }}
            >
              <RefreshIcon className="size-[13px]" />
              Refresh History
            </TintButton>
            {isOwner && (
              <TintButton tone="red" onClick={clear}>
                <TrashIcon className="size-[13px]" strokeWidth={2.5} />
                Clear History
              </TintButton>
            )}
          </>
        }
      />

      <DataTable columns={COLUMNS}>
        {history.length === 0 ? (
          <EmptyRow colSpan={COLUMNS.length}>No Reseller keys generated yet.</EmptyRow>
        ) : (
          history.map((item) => (
            <Row key={item.key}>
              <Cell className="font-mono text-[#10b981]">{item.key}</Cell>
              <Cell>
                <PackageBadge>{item.package}</PackageBadge>
              </Cell>
              <Cell>{item.duration} Days</Cell>
              <Cell className="font-semibold text-[#e62843]">{item.creator}</Cell>
              <Cell>{item.date}</Cell>
            </Row>
          ))
        )}
      </DataTable>
    </Card>
  );
}
