"use client";

import { useMemo } from "react";

import { RefreshIcon, TrashIcon } from "@/components/icons";
import { TintButton } from "@/components/ui/buttons";
import { PackageBadge } from "@/components/ui/Badge";
import { keyValidity } from "@/lib/packages";
import { Card, CardHeader } from "@/components/ui/Card";
import { Cell, DataTable, EmptyRow, Row } from "@/components/ui/Table";
import { useToast } from "@/components/ui/Toast";
import { del } from "@/lib/client-api";
import { useDashboard } from "@/lib/store";
import type { KeyRecord } from "@/lib/types";

const COLUMNS = ["License Key", "Package", "Validity", "Creator", "Created On"];

export default function ResellerHistoryPage() {
  const toast = useToast();
  const refresh = useDashboard((s) => s.refresh);
  const isOwner = useDashboard((s) => s.user?.role === "OWNER");
  // Same as the owner history: derive from a stable slice, never from a
  // selector that allocates.
  const keyHistory = useDashboard((s) => s.db.cheatExeKeyHistory);
  const history = useMemo(() => keyHistory.filter((k) => k.creator !== "admin"), [keyHistory]);

  const clear = async () => {
    if (!confirm("Clear this key history permanently?")) return;
    try {
      await del("/api/history?scope=reseller");
      await refresh();
      toast("Key history cleared successfully.", "success");
    } catch (err) {
      toast((err as Error).message, "error");
    }
  };

  return (
    <Card flat>
      <CardHeader
        title={isOwner ? "Reseller Key History" : "My Key History"}
        subtitle="Keys generated by resellers."
        actions={
          <>
            <TintButton
              tone="green"
              onClick={async () => {
                await refresh();
                toast("Key history refreshed.", "success");
              }}
            >
              <RefreshIcon className="size-[13px]" />
              Refresh History
            </TintButton>
            {isOwner && (
              <TintButton tone="red" onClick={clear}>
                <TrashIcon className="size-[13px]" strokeWidth={2.5} />
                Clear History
              </TintButton>
            )}
          </>
        }
      />

      <DataTable columns={COLUMNS}>
        {history.length === 0 ? (
          <EmptyRow colSpan={COLUMNS.length}>No Reseller keys generated yet.</EmptyRow>
        ) : (
          history.map((item) => (
            <Row key={item.key}>
              <Cell className="font-mono text-[#10b981]">{item.key}</Cell>
              <Cell>
                <PackageBadge>{item.package}</PackageBadge>
              </Cell>
              <ValidityCell item={item} />
              <Cell className="font-semibold text-[#e62843]">{item.creator}</Cell>
              <Cell>{item.date}</Cell>
            </Row>
          ))
        )}
      </DataTable>
    </Card>
  );
}

/** Shown for keys minted before the provider's own parameter name was used. */
const UNCONFIRMED_VALIDITY =
  "This is what was asked for, not what was confirmed. The key was generated before the panel " +
  "sent the validity under the name the provider reads, so the provider may have applied its own " +
  "default instead. Check the TERMINALX999 portal for this key.";

/**
 * The validity column.
 *
 * Keys minted before the panel sent `days` rather than `duration` may have
 * been given the provider's default instead of the number chosen, so those
 * are greyed and italic with the doubt in the tooltip. Printing one as
 * though it were confirmed is how a key the provider issued as 30 days
 * came to be listed here, flatly, as "10 Days".
 */
function ValidityCell({ item }: { item: KeyRecord }) {
  const { label, certain } = keyValidity(item);
  return (
    <Cell
      className={certain ? undefined : "text-muted italic"}
      title={certain ? undefined : UNCONFIRMED_VALIDITY}
    >
      {label}
    </Cell>
  );
}
