"use client";

import { useMemo } from "react";

import { RefreshIcon, TrashIcon } from "@/components/icons";
import { CopyButton, TintButton } from "@/components/ui/buttons";
import { PackageBadge } from "@/components/ui/Badge";
import { keyValidity } from "@/lib/packages";
import { Card, CardHeader } from "@/components/ui/Card";
import { Cell, DataTable, EmptyRow, Row } from "@/components/ui/Table";
import { useToast } from "@/components/ui/Toast";
import { del } from "@/lib/client-api";
import { useDashboard } from "@/lib/store";
import type { KeyRecord } from "@/lib/types";
import { formatStampForDisplay } from "@/lib/utils";

const COLUMNS = ["License Key", "Package", "Validity", "Created On", "Actions"];

export default function OwnerHistoryPage() {
  const toast = useToast();
  const refresh = useDashboard((s) => s.refresh);
  // Select the stable slice and derive here: a selector that returns a
  // fresh array each call breaks useSyncExternalStore in Zustand v5.
  const keyHistory = useDashboard((s) => s.db.cheatExeKeyHistory);
  const history = useMemo(() => keyHistory.filter((k) => k.creator === "admin"), [keyHistory]);

  const clear = async () => {
    if (!confirm("Are you sure you want to permanently clear all Owner key history?")) return;
    try {
      await del("/api/history?scope=owner");
      await refresh();
      toast("Owner key history cleared successfully.", "success");
    } catch (err) {
      toast((err as Error).message, "error");
    }
  };

  return (
    <Card flat>
      <CardHeader
        title="Owner Key History"
        subtitle="Keys generated by the Owner."
        actions={
          <>
            <TintButton
              tone="green"
              onClick={async () => {
                await refresh();
                toast("Owner key history refreshed.", "success");
              }}
            >
              <RefreshIcon className="size-[13px]" />
              Refresh History
            </TintButton>
            <TintButton tone="red" onClick={clear}>
              <TrashIcon className="size-[13px]" strokeWidth={2.5} />
              Clear History
            </TintButton>
          </>
        }
      />

      <DataTable columns={COLUMNS}>
        {history.length === 0 ? (
          <EmptyRow colSpan={COLUMNS.length}>No Owner keys generated yet.</EmptyRow>
        ) : (
          history.map((item) => (
            <Row key={item.key}>
              <Cell className="font-mono text-[#10b981]">{item.key}</Cell>
              <Cell>
                <PackageBadge>{item.package}</PackageBadge>
              </Cell>
              <ValidityCell item={item} />
              <Cell>{formatStampForDisplay(item.date)}</Cell>
              <Cell>
                <CopyButton
                  onClick={async () => {
                    await navigator.clipboard.writeText(item.key);
                    toast("Copied!", "success");
                  }}
                >
                  Copy
                </CopyButton>
              </Cell>
            </Row>
          ))
        )}
      </DataTable>
    </Card>
  );
}

/** Shown for keys minted before the provider's own parameter name was used. */
const UNCONFIRMED_VALIDITY =
  "This is what was asked for, not what was confirmed. The key was generated before the panel " +
  "sent the validity under the name the provider reads, so the provider may have applied its own " +
  "default instead. Check the TERMINALX999 portal for this key.";

/**
 * The validity column.
 *
 * Keys minted before the panel sent `days` rather than `duration` may have
 * been given the provider's default instead of the number chosen, so those
 * are greyed and italic with the doubt in the tooltip. Printing one as
 * though it were confirmed is how a key the provider issued as 30 days
 * came to be listed here, flatly, as "10 Days".
 */
function ValidityCell({ item }: { item: KeyRecord }) {
  const { label, certain } = keyValidity(item);
  return (
    <Cell
      className={certain ? undefined : "text-muted italic"}
      title={certain ? undefined : UNCONFIRMED_VALIDITY}
    >
      {label}
    </Cell>
  );
}
