"use client";

import { useMemo } from "react";

import { RefreshIcon, TrashIcon } from "@/components/icons";
import { CopyButton, TintButton } from "@/components/ui/buttons";
import { PackageBadge } from "@/components/ui/Badge";
import { Card, CardHeader } from "@/components/ui/Card";
import { Cell, DataTable, EmptyRow, Row } from "@/components/ui/Table";
import { useToast } from "@/components/ui/Toast";
import { del } from "@/lib/client-api";
import { useDashboard } from "@/lib/store";

const COLUMNS = ["License Key", "Package", "Duration", "Created On", "Actions"];

export default function OwnerHistoryPage() {
  const toast = useToast();
  const refresh = useDashboard((s) => s.refresh);
  // Select the stable slice and derive here: a selector that returns a
  // fresh array each call breaks useSyncExternalStore in Zustand v5.
  const keyHistory = useDashboard((s) => s.db.cheatExeKeyHistory);
  const history = useMemo(() => keyHistory.filter((k) => k.creator === "admin"), [keyHistory]);

  const clear = async () => {
    if (!confirm("Are you sure you want to permanently clear all Owner key history?")) return;
    try {
      await del("/api/history?scope=owner");
      await refresh();
      toast("Owner key history cleared successfully.", "success");
    } catch (err) {
      toast((err as Error).message, "error");
    }
  };

  return (
    <Card flat>
      <CardHeader
        title="Owner Key History"
        subtitle="Keys generated by the Owner."
        actions={
          <>
            <TintButton
              tone="green"
              onClick={async () => {
                await refresh();
                toast("Owner key history refreshed.", "success");
              }}
            >
              <RefreshIcon className="size-[13px]" />
              Refresh History
            </TintButton>
            <TintButton tone="red" onClick={clear}>
              <TrashIcon className="size-[13px]" strokeWidth={2.5} />
              Clear History
            </TintButton>
          </>
        }
      />

      <DataTable columns={COLUMNS}>
        {history.length === 0 ? (
          <EmptyRow colSpan={COLUMNS.length}>No Owner keys generated yet.</EmptyRow>
        ) : (
          history.map((item) => (
            <Row key={item.key}>
              <Cell className="font-mono text-[#10b981]">{item.key}</Cell>
              <Cell>
                <PackageBadge>{item.package}</PackageBadge>
              </Cell>
              <Cell>{item.duration} Days</Cell>
              <Cell>{item.date}</Cell>
              <Cell>
                <CopyButton
                  onClick={async () => {
                    await navigator.clipboard.writeText(item.key);
                    toast("Copied!", "success");
                  }}
                >
                  Copy
                </CopyButton>
              </Cell>
            </Row>
          ))
        )}
      </DataTable>
    </Card>
  );
}
